# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.

# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.
title: Apurv Ghai
email: 
description: Hello, I’m Apurv —  a tech enthusiast who loves sharing practical insights. Real fixes. Real experiments. No fluff. Subscribe to Apurv’s Sandbox and get smarter with every post.
  #Write an awesome description for your new site here. You can edit this
  #line in _config.yml. It will appear in your document head meta (for
  #Google search results) and in your feed.xml site description.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://apurvghai.com" # the base hostname & protocol for your site, e.g. http://example.com
twitter_username: apurvgh
github_username:  apurvghai
author_first_name: Apurv
author_last_name: Ghai
substack_url: https://blogs.apurvghai.com
substack_subscribe_url: https://blogs.apurvghai.com/subscribe?utm_source=subscribe_content_block&simple=true&next=https%3A%2F%2Fblogs.apurvghai.com%2F
sass:
  style: :compressed
theme: jekyll-theme-primer
future: true
# Build settings
markdown: kramdown
highlighter: rouge
incremental: true
gist:
   noscript: false
kramdown:
   math_engine: mathjax
   syntax_highlighter: roug

plugins:
  - jekyll-feed
  - jekyll-menus
  - jekyll-seo-tag
  - jekyll-sitemap
disqus: apurv-blogs
feed:
 tags: true
 excerpt_only: true

# Exclude from processing.
# The following items will not be processed, by default. Create a custom list
# to override the default setting.
# exclude:
#   - Gemfile
#   - Gemfile.lock
#   - node_modules
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/  
repository: "apurvgh/apurvgh.github.io"
collections:
  posts:
    output: true

paginate: 10
paginate_path: "/page:num/"

image_pool:
  - /img/ai-startup-office-software-developer-typing-computer-keyboard-close-up.jpg
  - /img/programming-script-text-coding-words.jpg
  - /img/double-exposure-caucasian-man-virtual-reality-vr-headset-is-presumably-gamer-hacker-cracking-code-into-secure-network-server-with-lines-code.jpg
  - /img/technician-looking-ui-computer-monitor-executing-programming-code.jpg
